name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs exemple.php --standard=PSR1,PSR12