  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install cs2pr
      run: wget -q https://cs.symfony.com/cs2pr -O cs2pr && chmod +x cs2pr

    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs exemple.php --standard=PSR1,PSR12 exemple.php | ./cs2pr


